<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            🎯 2048
        </h2>
    </x-slot>

    <div class="content">
        <div class="max-w-4xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-6">
                <!-- Back Link -->
                <div class="mb-4">
                    <a href="{{ route('games') }}" class="settings-button" style="display: inline-block; text-decoration: none;">
                        ← Retour aux jeux
                    </a>
                </div>

                <!-- Title -->
                <div class="mb-6">
                    <h3 class="text-2xl font-bold mb-1">🎯 2048</h3>
                    <p class="text-sm text-gray-500">Fusionnez les tuiles pour atteindre 2048 !</p>
                </div>

                <!-- Score Section -->
                <div class="stats-grid mb-6">
                    <div class="stat-card">
                        <div class="stat-number" id="score">0</div>
                        <div class="stat-label">Score</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-number" id="bestScore">0</div>
                        <div class="stat-label">Meilleur</div>
                    </div>
                    <div class="stat-card" style="display: flex; align-items: center; justify-content: center;">
                        <button id="newGameBtn" class="settings-button" style="width: 100%; margin: 0;">🔄 Nouveau Jeu</button>
                    </div>
                </div>

                <!-- Game Over/Win Message -->
                <div id="gameMessage" style="display: none; margin-bottom: 20px;">
                    <div id="messageBox" style="padding: 12px; border-radius: 6px; text-align: center;">
                        <strong style="font-size: 18px;" id="messageTitle"></strong>
                        <p style="margin-top: 4px;" id="messageText"></p>
                    </div>
                </div>

                <!-- Game Board -->
                <div style="display: flex; justify-content: center; margin-bottom: 24px;">
                    <div style="background: #bbada0; border-radius: 8px; padding: 12px; display: inline-block;">
                        <div id="board" style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px;">
                            <!-- Grid cells will be generated by JavaScript -->
                        </div>
                    </div>
                </div>

                <!-- Instructions -->
                <div class="settings-card">
                    <h4 style="margin-bottom: 12px;">📋 Instructions</h4>
                    <ul style="color: #6b7280; font-size: 14px; line-height: 1.8; padding-left: 20px;">
                        <li>Utilisez les <strong>flèches du clavier</strong> (↑ ↓ ← →) pour déplacer les tuiles</li>
                        <li>Quand deux tuiles avec le <strong>même nombre</strong> se touchent, elles <strong>fusionnent</strong></li>
                        <li>Chaque fusion double la valeur de la tuile</li>
                        <li>Atteignez la tuile <strong>2048</strong> pour gagner !</li>
                        <li>Le jeu se termine quand aucun mouvement n'est possible</li>
                        <li>Votre meilleur score est sauvegardé automatiquement</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script>
        const boardElement = document.getElementById('board');
        const scoreElement = document.getElementById('score');
        const bestScoreElement = document.getElementById('bestScore');
        const newGameBtn = document.getElementById('newGameBtn');
        const gameMessage = document.getElementById('gameMessage');
        const messageBox = document.getElementById('messageBox');
        const messageTitle = document.getElementById('messageTitle');
        const messageText = document.getElementById('messageText');

        const gridSize = 4;
        let board = [];
        let score = 0;
        let bestScore = localStorage.getItem('2048BestScore') || 0;
        let gameWon = false;

        bestScoreElement.textContent = bestScore;

        const tileColors = {
            2: '#eee4da', 4: '#ede0c8', 8: '#f2b179', 16: '#f59563',
            32: '#f67c5f', 64: '#f65e3b', 128: '#edcf72', 256: '#edcc61',
            512: '#edc850', 1024: '#edc53f', 2048: '#edc22e', 4096: '#3c3a32', 8192: '#3c3a32'
        };

        function initGame() {
            board = Array(gridSize).fill(null).map(() => Array(gridSize).fill(0));
            score = 0;
            gameWon = false;
            scoreElement.textContent = '0';
            gameMessage.style.display = 'none';
            
            addNewTile();
            addNewTile();
            renderBoard();
        }

        function renderBoard() {
            boardElement.innerHTML = '';
            
            for (let i = 0; i < gridSize; i++) {
                for (let j = 0; j < gridSize; j++) {
                    const tile = document.createElement('div');
                    const value = board[i][j];
                    
                    tile.style.cssText = 'width: 100px; height: 100px; border-radius: 6px; display: flex; align-items: center; justify-content: center; font-weight: bold; font-size: 24px; transition: all 0.15s;';
                    
                    if (value === 0) {
                        tile.style.background = '#cdc1b4';
                        tile.style.color = 'transparent';
                    } else {
                        tile.style.background = tileColors[value] || '#3c3a32';
                        tile.style.color = value > 4 ? '#f9f6f2' : '#776e65';
                        tile.textContent = value;
                        tile.style.boxShadow = '0 2px 4px rgba(0,0,0,0.2)';
                    }
                    
                    boardElement.appendChild(tile);
                }
            }
        }

        function addNewTile() {
            const emptyCells = [];
            
            for (let i = 0; i < gridSize; i++) {
                for (let j = 0; j < gridSize; j++) {
                    if (board[i][j] === 0) {
                        emptyCells.push({ i, j });
                    }
                }
            }
            
            if (emptyCells.length > 0) {
                const { i, j } = emptyCells[Math.floor(Math.random() * emptyCells.length)];
                board[i][j] = Math.random() < 0.9 ? 2 : 4;
            }
        }

        function move(direction) {
            let moved = false;
            const oldBoard = board.map(row => [...row]);
            
            if (direction === 'left' || direction === 'right') {
                for (let i = 0; i < gridSize; i++) {
                    const row = direction === 'left' ? board[i] : board[i].reverse();
                    const newRow = slideAndMerge(row);
                    board[i] = direction === 'left' ? newRow : newRow.reverse();
                }
            } else {
                for (let j = 0; j < gridSize; j++) {
                    const column = [];
                    for (let i = 0; i < gridSize; i++) {
                        column.push(board[i][j]);
                    }
                    
                    const newColumn = direction === 'up' ? slideAndMerge(column) : slideAndMerge(column.reverse()).reverse();
                    
                    for (let i = 0; i < gridSize; i++) {
                        board[i][j] = newColumn[i];
                    }
                }
            }
            
            for (let i = 0; i < gridSize; i++) {
                for (let j = 0; j < gridSize; j++) {
                    if (oldBoard[i][j] !== board[i][j]) {
                        moved = true;
                        break;
                    }
                }
                if (moved) break;
            }
            
            if (moved) {
                addNewTile();
                renderBoard();
                
                if (score > bestScore) {
                    bestScore = score;
                    bestScoreElement.textContent = bestScore;
                    localStorage.setItem('2048BestScore', bestScore);
                }
                
                checkWin();
                checkGameOver();
            }
        }

        function slideAndMerge(line) {
            let newLine = line.filter(val => val !== 0);
            
            for (let i = 0; i < newLine.length - 1; i++) {
                if (newLine[i] === newLine[i + 1]) {
                    newLine[i] *= 2;
                    score += newLine[i];
                    scoreElement.textContent = score;
                    newLine.splice(i + 1, 1);
                }
            }
            
            while (newLine.length < gridSize) {
                newLine.push(0);
            }
            
            return newLine;
        }

        function checkWin() {
            if (gameWon) return;
            
            for (let i = 0; i < gridSize; i++) {
                for (let j = 0; j < gridSize; j++) {
                    if (board[i][j] === 2048) {
                        gameWon = true;
                        showMessage('success', '🎉 Vous avez gagné !', 'Vous avez atteint 2048 ! Continuez pour un score encore plus élevé.');
                        return;
                    }
                }
            }
        }

        function checkGameOver() {
            for (let i = 0; i < gridSize; i++) {
                for (let j = 0; j < gridSize; j++) {
                    if (board[i][j] === 0) return;
                }
            }
            
            for (let i = 0; i < gridSize; i++) {
                for (let j = 0; j < gridSize; j++) {
                    const current = board[i][j];
                    if (j < gridSize - 1 && current === board[i][j + 1]) return;
                    if (i < gridSize - 1 && current === board[i + 1][j]) return;
                }
            }
            
            showMessage('error', '😢 Game Over !', `Score final: ${score}. Essayez de battre votre record !`);
        }

        function showMessage(type, title, text) {
            messageTitle.textContent = title;
            messageText.textContent = text;
            
            if (type === 'success') {
                messageBox.style.background = '#dcfce7';
                messageBox.style.border = '1px solid #86efac';
                messageBox.style.color = '#166534';
            } else {
                messageBox.style.background = '#fee2e2';
                messageBox.style.border = '1px solid #fca5a5';
                messageBox.style.color = '#991b1b';
            }
            
            gameMessage.style.display = 'block';
        }

        document.addEventListener('keydown', (e) => {
            if (['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'].includes(e.key)) {
                e.preventDefault();
                
                switch (e.key) {
                    case 'ArrowUp': move('up'); break;
                    case 'ArrowDown': move('down'); break;
                    case 'ArrowLeft': move('left'); break;
                    case 'ArrowRight': move('right'); break;
                }
            }
        });

        newGameBtn.addEventListener('click', initGame);

        initGame();
    </script>
</x-app-layout>
