<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            🎴 Memory Cards
        </h2>
    </x-slot>

    <div class="content">
        <div class="max-w-4xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-6">
                <!-- Back Link -->
                <div class="mb-4">
                    <a href="{{ route('games') }}" class="settings-button" style="display: inline-block; text-decoration: none;">
                        ← Retour aux jeux
                    </a>
                </div>

                <!-- Title -->
                <div class="mb-6">
                    <h3 class="text-2xl font-bold mb-1">🎴 Memory Cards</h3>
                    <p class="text-sm text-gray-500">Testez votre mémoire en trouvant les paires !</p>
                </div>

                <!-- Game Stats -->
                <div class="stats-grid mb-6">
                    <div class="stat-card">
                        <div class="stat-number" id="moves">0</div>
                        <div class="stat-label">Coups</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-number" id="pairs">0 / 8</div>
                        <div class="stat-label">Paires trouvées</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-number" id="timer">0:00</div>
                        <div class="stat-label">Temps</div>
                    </div>
                    <div class="stat-card" style="display: flex; align-items: center; justify-content: center;">
                        <button id="resetBtn" class="settings-button" style="width: 100%; margin: 0;">🔄 Recommencer</button>
                    </div>
                </div>

                <!-- Victory Message -->
                <div id="victoryMessage" style="display: none; margin-bottom: 20px; padding: 12px; background: #dcfce7; border: 1px solid #86efac; border-radius: 6px; color: #166534; text-align: center;">
                    <strong style="font-size: 18px;">🎉 Félicitations !</strong>
                    <p style="margin-top: 4px;">Vous avez trouvé toutes les paires en <strong><span id="finalMoves"></span> coups</strong> et <strong><span id="finalTime"></span></strong> !</p>
                </div>

                <!-- Game Board -->
                <div style="display: flex; justify-content: center; margin-bottom: 24px;">
                    <div id="board" style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; max-width: 600px;">
                        <!-- Cards will be generated by JavaScript -->
                    </div>
                </div>

                <!-- Instructions -->
                <div class="settings-card">
                    <h4 style="margin-bottom: 12px;">📋 Instructions</h4>
                    <ul style="color: #6b7280; font-size: 14px; line-height: 1.8; padding-left: 20px;">
                        <li>Cliquez sur une carte pour la retourner</li>
                        <li>Trouvez la <strong>carte identique</strong> en cliquant sur une deuxième carte</li>
                        <li>Si les deux cartes correspondent, elles restent retournées</li>
                        <li>Sinon, elles se retournent automatiquement</li>
                        <li>Trouvez les <strong>8 paires</strong> pour gagner !</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script>
        const board = document.getElementById('board');
        const movesElement = document.getElementById('moves');
        const pairsElement = document.getElementById('pairs');
        const timerElement = document.getElementById('timer');
        const resetBtn = document.getElementById('resetBtn');
        const victoryMessage = document.getElementById('victoryMessage');
        const finalMoves = document.getElementById('finalMoves');
        const finalTime = document.getElementById('finalTime');

        const emojis = ['🎮', '🎯', '🎲', '🎪', '🎨', '🎭', '🎸', '🎹'];
        let cards = [];
        let flippedCards = [];
        let matchedPairs = 0;
        let moves = 0;
        let timerInterval;
        let seconds = 0;

        function initGame() {
            board.innerHTML = '';
            cards = [];
            flippedCards = [];
            matchedPairs = 0;
            moves = 0;
            seconds = 0;
            
            movesElement.textContent = '0';
            pairsElement.textContent = '0 / 8';
            timerElement.textContent = '0:00';
            victoryMessage.style.display = 'none';
            
            const cardValues = [...emojis, ...emojis];
            shuffleArray(cardValues);
            
            cardValues.forEach((emoji, index) => {
                const card = document.createElement('div');
                card.style.cssText = 'background: linear-gradient(135deg, #6366f1, #8b5cf6); border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); height: 120px; display: flex; align-items: center; justify-content: center; font-size: 48px; cursor: pointer; transition: all 0.3s; color: white; font-weight: bold;';
                card.dataset.emoji = emoji;
                card.dataset.index = index;
                card.innerHTML = '?';
                card.addEventListener('click', flipCard);
                card.addEventListener('mouseenter', function() {
                    if (!this.classList.contains('flipped') && !this.classList.contains('matched')) {
                        this.style.transform = 'scale(1.05)';
                    }
                });
                card.addEventListener('mouseleave', function() {
                    if (!this.classList.contains('flipped') && !this.classList.contains('matched')) {
                        this.style.transform = 'scale(1)';
                    }
                });
                board.appendChild(card);
                cards.push(card);
            });
            
            clearInterval(timerInterval);
            timerInterval = setInterval(updateTimer, 1000);
        }

        function shuffleArray(array) {
            for (let i = array.length - 1; i > 0; i--) {
                const j = Math.floor(Math.random() * (i + 1));
                [array[i], array[j]] = [array[j], array[i]];
            }
        }

        function updateTimer() {
            seconds++;
            const mins = Math.floor(seconds / 60);
            const secs = seconds % 60;
            timerElement.textContent = `${mins}:${secs.toString().padStart(2, '0')}`;
        }

        function flipCard(e) {
            const card = e.currentTarget;
            
            if (card.classList.contains('flipped') || card.classList.contains('matched')) {
                return;
            }
            
            if (flippedCards.length >= 2) {
                return;
            }
            
            card.classList.add('flipped');
            card.innerHTML = card.dataset.emoji;
            card.style.background = 'white';
            card.style.color = 'black';
            flippedCards.push(card);
            
            if (flippedCards.length === 2) {
                moves++;
                movesElement.textContent = moves;
                
                setTimeout(checkMatch, 800);
            }
        }

        function checkMatch() {
            const [card1, card2] = flippedCards;
            
            if (card1.dataset.emoji === card2.dataset.emoji) {
                card1.classList.add('matched');
                card2.classList.add('matched');
                card1.style.cursor = 'default';
                card2.style.cursor = 'default';
                card1.style.background = '#dcfce7';
                card2.style.background = '#dcfce7';
                card1.style.color = '#166534';
                card2.style.color = '#166534';
                
                matchedPairs++;
                pairsElement.textContent = `${matchedPairs} / 8`;
                
                if (matchedPairs === 8) {
                    gameWon();
                }
            } else {
                card1.classList.remove('flipped');
                card2.classList.remove('flipped');
                card1.innerHTML = '?';
                card2.innerHTML = '?';
                card1.style.background = 'linear-gradient(135deg, #6366f1, #8b5cf6)';
                card2.style.background = 'linear-gradient(135deg, #6366f1, #8b5cf6)';
                card1.style.color = 'white';
                card2.style.color = 'white';
            }
            
            flippedCards = [];
        }

        function gameWon() {
            clearInterval(timerInterval);
            
            const mins = Math.floor(seconds / 60);
            const secs = seconds % 60;
            const timeString = mins > 0 ? `${mins}min ${secs}s` : `${secs}s`;
            
            finalMoves.textContent = moves;
            finalTime.textContent = timeString;
            victoryMessage.style.display = 'block';
        }

        resetBtn.addEventListener('click', initGame);

        initGame();
    </script>
</x-app-layout>
