<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            ⭕ Tic-Tac-Toe
        </h2>
    </x-slot>

    <div class="content">
        <div class="max-w-4xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-6">
                <!-- Back Link -->
                <div class="mb-4">
                    <a href="{{ route('games') }}" class="settings-button" style="display: inline-block; text-decoration: none;">
                        ← Retour aux jeux
                    </a>
                </div>

                <!-- Title -->
                <div class="mb-6">
                    <h3 class="text-2xl font-bold mb-1">⭕ Tic-Tac-Toe</h3>
                    <p class="text-sm text-gray-500">Affrontez l'ordinateur et alignez 3 symboles pour gagner !</p>
                </div>

                <!-- Game Status -->
                <div style="text-align: center; margin-bottom: 20px;">
                    <div id="gameStatus" style="font-size: 18px; font-weight: 600; color: #6366f1;">Votre tour (X)</div>
                    <div id="gameResult" style="display: none; margin-top: 8px; font-size: 16px; font-weight: 600;"></div>
                </div>

                <!-- Game Board -->
                <div style="display: flex; justify-content: center; margin-bottom: 24px;">
                    <div id="board" style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; width: 360px;">
                        <!-- Cells will be generated by JavaScript -->
                    </div>
                </div>

                <!-- Controls -->
                <div style="text-align: center; margin-bottom: 24px;">
                    <button id="resetBtn" class="settings-button" style="display: inline-block;">🔄 Nouvelle Partie</button>
                </div>

                <!-- Stats -->
                <div class="stats-grid mb-6">
                    <div class="stat-card" style="background: #dcfce7;">
                        <div class="stat-number" id="playerWins" style="color: #16a34a;">0</div>
                        <div class="stat-label">Victoires</div>
                    </div>
                    <div class="stat-card" style="background: #f3f4f6;">
                        <div class="stat-number" id="draws" style="color: #6b7280;">0</div>
                        <div class="stat-label">Égalités</div>
                    </div>
                    <div class="stat-card" style="background: #fee2e2;">
                        <div class="stat-number" id="computerWins" style="color: #dc2626;">0</div>
                        <div class="stat-label">Défaites</div>
                    </div>
                </div>

                <!-- Instructions -->
                <div class="settings-card">
                    <h4 style="margin-bottom: 12px;">📋 Instructions</h4>
                    <ul style="color: #6b7280; font-size: 14px; line-height: 1.8; padding-left: 20px;">
                        <li>Vous jouez avec les <strong>X</strong>, l'ordinateur avec les <strong>O</strong></li>
                        <li>Cliquez sur une case vide pour placer votre symbole</li>
                        <li>Alignez 3 symboles horizontalement, verticalement ou en diagonale pour gagner</li>
                        <li>L'ordinateur utilise une <strong>intelligence artificielle</strong> pour jouer</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script>
        const board = document.getElementById('board');
        const gameStatus = document.getElementById('gameStatus');
        const gameResult = document.getElementById('gameResult');
        const resetBtn = document.getElementById('resetBtn');
        const playerWinsElement = document.getElementById('playerWins');
        const computerWinsElement = document.getElementById('computerWins');
        const drawsElement = document.getElementById('draws');

        let cells = [];
        let currentPlayer = 'X';
        let gameActive = true;
        let boardState = ['', '', '', '', '', '', '', '', ''];

        let stats = {
            playerWins: 0,
            computerWins: 0,
            draws: 0
        };

        const savedStats = localStorage.getItem('tictactoeStats');
        if (savedStats) {
            stats = JSON.parse(savedStats);
            updateStatsDisplay();
        }

        function initBoard() {
            board.innerHTML = '';
            cells = [];
            boardState = ['', '', '', '', '', '', '', '', ''];
            currentPlayer = 'X';
            gameActive = true;
            gameStatus.textContent = 'Votre tour (X)';
            gameResult.style.display = 'none';
            
            for (let i = 0; i < 9; i++) {
                const cell = document.createElement('div');
                cell.style.cssText = 'background: white; border: 2px solid #e5e7eb; border-radius: 8px; height: 110px; display: flex; align-items: center; justify-content: center; font-size: 48px; font-weight: bold; cursor: pointer; transition: all 0.2s;';
                cell.dataset.index = i;
                cell.addEventListener('click', handleCellClick);
                cell.addEventListener('mouseenter', () => {
                    if (gameActive && boardState[i] === '') {
                        cell.style.background = '#f3f4f6';
                    }
                });
                cell.addEventListener('mouseleave', () => {
                    if (boardState[i] === '') {
                        cell.style.background = 'white';
                    }
                });
                board.appendChild(cell);
                cells.push(cell);
            }
        }

        function handleCellClick(e) {
            const index = e.target.dataset.index;
            
            if (!gameActive || boardState[index] !== '' || currentPlayer !== 'X') {
                return;
            }
            
            makeMove(index, 'X');
            
            if (gameActive) {
                setTimeout(computerMove, 500);
            }
        }

        function makeMove(index, player) {
            boardState[index] = player;
            cells[index].textContent = player;
            cells[index].style.color = player === 'X' ? '#6366f1' : '#ef4444';
            cells[index].style.cursor = 'default';
            cells[index].style.background = '#fafafa';
            
            if (checkWinner(player)) {
                endGame(player);
            } else if (boardState.every(cell => cell !== '')) {
                endGame('draw');
            } else {
                currentPlayer = player === 'X' ? 'O' : 'X';
                gameStatus.textContent = currentPlayer === 'X' ? 'Votre tour (X)' : 'Tour de l\'ordinateur (O)';
            }
        }

        function computerMove() {
            if (!gameActive) return;
            
            gameStatus.textContent = 'Tour de l\'ordinateur (O)...';
            
            const bestMove = findBestMove();
            makeMove(bestMove, 'O');
        }

        function minimax(board, depth, isMaximizing) {
            if (checkWinner('O')) return 10 - depth;
            if (checkWinner('X')) return depth - 10;
            if (board.every(cell => cell !== '')) return 0;
            
            if (isMaximizing) {
                let bestScore = -Infinity;
                for (let i = 0; i < 9; i++) {
                    if (board[i] === '') {
                        board[i] = 'O';
                        const score = minimax(board, depth + 1, false);
                        board[i] = '';
                        bestScore = Math.max(score, bestScore);
                    }
                }
                return bestScore;
            } else {
                let bestScore = Infinity;
                for (let i = 0; i < 9; i++) {
                    if (board[i] === '') {
                        board[i] = 'X';
                        const score = minimax(board, depth + 1, true);
                        board[i] = '';
                        bestScore = Math.min(score, bestScore);
                    }
                }
                return bestScore;
            }
        }

        function findBestMove() {
            let bestScore = -Infinity;
            let bestMove = -1;
            
            for (let i = 0; i < 9; i++) {
                if (boardState[i] === '') {
                    boardState[i] = 'O';
                    const score = minimax([...boardState], 0, false);
                    boardState[i] = '';
                    
                    if (score > bestScore) {
                        bestScore = score;
                        bestMove = i;
                    }
                }
            }
            
            return bestMove;
        }

        function checkWinner(player) {
            const winPatterns = [
                [0, 1, 2], [3, 4, 5], [6, 7, 8],
                [0, 3, 6], [1, 4, 7], [2, 5, 8],
                [0, 4, 8], [2, 4, 6]
            ];
            
            return winPatterns.some(pattern => {
                return pattern.every(index => boardState[index] === player);
            });
        }

        function endGame(winner) {
            gameActive = false;
            gameResult.style.display = 'block';
            
            if (winner === 'X') {
                gameResult.textContent = '🎉 Vous avez gagné !';
                gameResult.style.color = '#16a34a';
                stats.playerWins++;
            } else if (winner === 'O') {
                gameResult.textContent = '🤖 L\'ordinateur a gagné !';
                gameResult.style.color = '#dc2626';
                stats.computerWins++;
            } else {
                gameResult.textContent = '🤝 Match nul !';
                gameResult.style.color = '#6b7280';
                stats.draws++;
            }
            
            gameStatus.textContent = 'Partie terminée';
            updateStatsDisplay();
            saveStats();
        }

        function updateStatsDisplay() {
            playerWinsElement.textContent = stats.playerWins;
            computerWinsElement.textContent = stats.computerWins;
            drawsElement.textContent = stats.draws;
        }

        function saveStats() {
            localStorage.setItem('tictactoeStats', JSON.stringify(stats));
        }

        resetBtn.addEventListener('click', initBoard);

        initBoard();
    </script>
</x-app-layout>
